/*
project SE 

amir bouferkas G3
ben arouche saber G3


*/

// includes 
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <semaphore.h>
#include <time.h>


//matrix and buffer size
#define N 3

// globale variables

// matrix 
int B[N][N], C[N][N], A[N][N];

//buffer
int T[N];

//semaphores
sem_t mut_pro_con[N], mut;



// the productor function
void *producer(void *arg)
{
    int id = (*(int *)arg);// the corresponding producer thread id 
    int P[N];//stocking the line before the access the the buffer

    printf("Producer %d started\n", id); // debuging messege 

    for (int i = 0; i < N; i++)
    {
        P[i] = 0;// the initialization of P with the defult value (0)

        for (int j = 0; j < N; j++)
        {
            P[i] += B[id][j] * C[j][i]; // calculing the line
        }
    }

    // access to the buffer 

    sem_wait(&mut);//waiting for the permission to access

    for (int i = 0; i < N; i++)
    {
        T[i] = P[i]; // filling the buffer
    }
    
    sem_post(&mut_pro_con[id]);// givinng permission to the corresponding consumer to access the buffer

    printf("Producer %d completed\n", id);// debuging messege 

    return NULL;
}



// the consumer function 
void *consumer(void *arg)
{
    int id = (*(int *)arg);// the corresponding consumer thread id 

    printf("Consumer %d started\n", id);// debuging messege 

    sem_wait(&mut_pro_con[id]);// waiting for the permission to access the buffer form the corresponding producer 

    for (int i = 0; i < N; i++)
    {
        A[id][i] = T[i]; //putting the buffer values in the correct place from the matric A
    }
    sem_post(&mut); // give the permission to access the buffer to the next producer

    printf("Consumer %d completed\n", id);// debuging messege 

    return NULL;
}



// the functon to randomly fill a matrix
void fillRandomly(int M[N][N]) {
    for (int i = 0; i < N; i++) {
        for (int j = 0; j < N; j++) {
            M[i][j] = rand() % 100; // generating random values from the range[0 99] and put them in the matrix
        }
    }
}

// the function to display a matrix
void display(int M[N][N]){

     for (int i = 0; i < N; i++)
    {
        printf("|");
        for (int j = 0; j < N; j++)
        {
            printf(" %d ",M[i][j]);
        }
        printf("|\n");
    }
    printf("\n\n");
    


}



int main()
{

    // the initialization of the semaphores
    sem_init(&mut, 0, 1);
    for (int i = 0; i < N; i++)
    {
        sem_init(&mut_pro_con[i], 0, 0);    
    }


    // the initialization A with the defult value (0)
    for (int i = 0; i < N; i++)
    {
        for (int j = 0; j < N; j++)
        {
            A[i][j] = 0;
        }
    }


    // the initialization B and C with random values

    srand(time(NULL));// ensure that the values generated by rand() are diffrent each time

    fillRandomly(B);
    fillRandomly(C);


    // Display matrix B 
    printf("la matrix B :\n\n");
    display(B);


    // Display matrix C
    printf("la matrix C :\n\n");
    display(C);


    // the initialization of the threads and they arguments 
    pthread_t pro[N], con[N];
    int pro_args[N], con_args[N];


    // creating the threads
    for (int i = 0; i < N; i++)
    {
        pro_args[i] = i;
        con_args[i] = i;

        pthread_create(&pro[i], NULL, producer, &pro_args[i]);
        pthread_create(&con[i], NULL, consumer, &con_args[i]);
    }


    // joining threads
    for (int i = 0; i < N; i++)
    {
        pthread_join(pro[i], NULL);
        pthread_join(con[i], NULL);
    }
    printf("\n");


    // Display matrix A
    printf("la matrix A :\n\n");
    display(A);
    

    // destroying the semaphoress
    sem_destroy(&mut);
    for (int i = 0; i < N; i++)
    {
        sem_destroy(&mut_pro_con[i]);
    }

    return 0;
}